namespace QYMSERVER.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Add_AllEntity_V1 : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.H_EQUIPMENT_PHOTOETCHING",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        EquipmentID = c.Int(nullable: false),
                        EquipmentName = c.String(),
                        EquipmentStatus = c.Decimal(nullable: false, precision: 18, scale: 2),
                        EquipmentSchedule = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.H_EQUIPMENT_REPAIR",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        EquipmentID = c.String(),
                        MaintenanceType = c.String(),
                        MaintenanceDate = c.DateTime(),
                        MaintenanceOperatior = c.String(),
                        MaintenanceUsedTime = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.H_EQUIPMENTALARM",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        EquipmentID = c.Int(nullable: false),
                        AlarmType = c.String(),
                        AlarmStartTime = c.DateTime(),
                        AlarmEndTime = c.DateTime(),
                        AlarmDiscription = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CAMCRAFTCMDEQPCONFIGTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        SHEBEIPEIZHIZHILINGID = c.String(),
                        MASKBORDER = c.Int(nullable: false),
                        GRAPH2MASKUPLIMIT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GRAPH2MASKDWLIMIT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MASKTYPE = c.Int(nullable: false),
                        MASKSIZETYPE = c.Int(nullable: false),
                        MINLSAREA = c.Int(nullable: false),
                        MINLSUPLIMIT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MINLSDWLIMIT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CDUPLIMIT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CDDWLIMIT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        EMULTYPE = c.String(),
                        WRKCTRID = c.String(),
                        OBJECT = c.Int(nullable: false),
                        TOVERIFY = c.Int(nullable: false),
                        INVALID = c.Int(nullable: false),
                        VERIFYER = c.String(),
                        RECORDER = c.String(),
                        EFFECTTIMELIMIT = c.Int(nullable: false),
                        APPOINTDAY = c.DateTime(nullable: false),
                        APPOINTDAYTZID = c.Int(nullable: false),
                        TOVERIFYTIME = c.DateTime(nullable: false),
                        TOVERIFYTIMETZID = c.Int(nullable: false),
                        TOEFFECTTIME = c.DateTime(nullable: false),
                        TOEFFECTTIMETZID = c.Int(nullable: false),
                        RECORDTIME = c.DateTime(nullable: false),
                        RECORDTIMETZID = c.Int(nullable: false),
                        SENDDEPARTMENT = c.String(),
                        ACCEPTDEPARTMENT = c.String(),
                        TECHNUM = c.String(),
                        TECHNAME = c.String(),
                        TECHTARGET = c.String(),
                        TECHTYPE = c.Int(nullable: false),
                        MINLSTYPE = c.String(),
                        TRADEID = c.String(),
                        CUSTACCOUNT = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        MINLINETYPE = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CAMCRAFTCMDMATERIALTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        BANCAIPIPEIID = c.String(),
                        WRKCTRID = c.String(),
                        TOVERIFY = c.Int(nullable: false),
                        INVALID = c.Int(nullable: false),
                        VERIFYER = c.String(),
                        RECORDER = c.String(),
                        EFFECTTIMELIMIT = c.Int(nullable: false),
                        APPOINTDAY = c.DateTime(nullable: false),
                        APPOINTDAYTZID = c.Int(nullable: false),
                        TOVERIFYTIME = c.DateTime(nullable: false),
                        TOVERIFYTIMETZID = c.Int(nullable: false),
                        TOEFFECTTIME = c.DateTime(nullable: false),
                        TOEFFECTTIMETZID = c.Int(nullable: false),
                        RECORDTIME = c.DateTime(nullable: false),
                        RECORDTIMETZID = c.Int(nullable: false),
                        SENDDEPARTMENT = c.String(),
                        TECHNUM = c.String(),
                        TECHNAME = c.String(),
                        TECHTARGET = c.String(),
                        TECHTYPE = c.Int(nullable: false),
                        ITEMID = c.String(),
                        ACCEPTDEPARTMENT = c.String(),
                        ACCEPTDEPARTMENT2_ = c.String(),
                        ACCEPTDEPARTMENT3_ = c.String(),
                        ACCEPTDEPARTMENT4_ = c.String(),
                        ACCEPTDEPARTMENT5_ = c.String(),
                        ACCEPTDEPARTMENT6_ = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CAMCRAFTCMDTRADETABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        HANGYEPIPEIID = c.String(),
                        WRKCTRID = c.String(),
                        TRADEID = c.String(),
                        TOVERIFY = c.Int(nullable: false),
                        INVALID = c.Int(nullable: false),
                        VERIFYER = c.String(),
                        RECORDER = c.String(),
                        EFFECTTIMELIMIT = c.Int(nullable: false),
                        APPOINTDAY = c.DateTime(nullable: false),
                        APPOINTDAYTZID = c.Int(nullable: false),
                        TOVERIFYTIME = c.DateTime(nullable: false),
                        TOVERIFYTIMETZID = c.Int(nullable: false),
                        TOEFFECTTIME = c.DateTime(nullable: false),
                        TOEFFECTTIMETZID = c.Int(nullable: false),
                        RECORDTIME = c.DateTime(nullable: false),
                        RECORDTIMETZID = c.Int(nullable: false),
                        SENDDEPARTMENT = c.String(),
                        ACCEPTDEPARTMENT = c.String(),
                        TECHNUM = c.String(),
                        TECHNAME = c.String(),
                        TECHTARGET = c.String(),
                        TECHTYPE = c.Int(nullable: false),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        MURAVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CAMDESIGNPARAMTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        INVENTREFID = c.String(),
                        INVENTREFTRANSID = c.String(),
                        INVENTDIMID = c.String(),
                        CDPRECISION = c.String(),
                        MINLSWIDTH = c.String(),
                        MINLSTYPE = c.String(),
                        GRAPH2EDGE = c.String(),
                        GRAPHFEATRUES = c.String(),
                        MASKOUTLINE = c.String(),
                        WRKCTRID = c.String(),
                        MACHINENAME = c.String(),
                        LENS = c.String(),
                        QYBARCODE = c.String(),
                        CLIENTBARCODE = c.String(),
                        INVERT = c.Int(nullable: false),
                        ROTATE = c.Int(nullable: false),
                        MIRROR = c.Int(nullable: false),
                        CPMASKMIRROR = c.Int(nullable: false),
                        LASTMIRROR = c.Int(nullable: false),
                        ISDELMASKMARK = c.Int(nullable: false),
                        NETPTDENSITY = c.String(),
                        NETPTANGLE = c.String(),
                        APERTURERATIO = c.String(),
                        X1STEP = c.Int(nullable: false),
                        Y1STEP = c.Int(nullable: false),
                        X2STEP = c.Int(nullable: false),
                        Y2STEP = c.Int(nullable: false),
                        MASKSIZEX = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MASKSIZEY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MASKSIZEZ = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TEMPERATUREXPPB = c.Int(nullable: false),
                        TEMPERATUREYPPB = c.Int(nullable: false),
                        GRAPHSCALEXPPB = c.Int(nullable: false),
                        GRAPHSCALEYPPB = c.Int(nullable: false),
                        CRAFTSCALEXPPB = c.Int(nullable: false),
                        CRAFTSCALEYPPB = c.Int(nullable: false),
                        CRAFTSCALEORTHOPPB = c.Int(nullable: false),
                        DESIGNLASTSCALEXPPB = c.Int(nullable: false),
                        DESIGNLASTSCALEYPPB = c.Int(nullable: false),
                        DESIGNLASTSCALEX = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DESIGNLASTSCALEY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CRFIELDNAME1 = c.String(),
                        CRFIELDNAME2 = c.String(),
                        CRFIELDNAME3 = c.String(),
                        CRFIELDNAME4 = c.String(),
                        CRATIO1 = c.String(),
                        CRATIO2 = c.String(),
                        CRATIO3 = c.String(),
                        CRATIO4 = c.String(),
                        DESIGNFORMAT = c.String(),
                        TOPCELL = c.String(),
                        LAYLOGICALS = c.String(),
                        CELLPITCHX = c.String(),
                        CELLPITCHY = c.String(),
                        MEBENAME = c.String(),
                        STRIPEWIDTH = c.String(),
                        PIXELSIZE = c.String(),
                        STETCHMODE = c.String(),
                        ADDITIONALPIXEL = c.String(),
                        BIDIRECTION = c.String(),
                        LICBUFFERSIZE = c.String(),
                        OVERLAP = c.String(),
                        YSPEED = c.String(),
                        RESOLUTION = c.String(),
                        BIASX = c.String(),
                        BIASY = c.String(),
                        PROCESS = c.String(),
                        ORIGINTYPE = c.String(),
                        MEASURECDAMOUNT = c.String(),
                        MURAFUNCTION = c.String(),
                        PIXELPITCHX = c.String(),
                        PIXELPITCHY = c.String(),
                        CRAFTLAYERNAME = c.String(),
                        ADDEXPOSALAMOUNT = c.String(),
                        EXPOSELOCATION = c.String(),
                        OFFSETUP = c.String(),
                        OFFSETDW = c.String(),
                        OFFSETLE = c.String(),
                        OFFSETRI = c.String(),
                        CONVERTFORMAT = c.String(),
                        DESIGNNAME = c.String(),
                        JOBNAME = c.String(),
                        JOBID = c.String(),
                        CONVERTNAME = c.String(),
                        REBACKREMARK = c.String(),
                        CAMREMARK = c.String(),
                        WRKSTATUS = c.Int(nullable: false),
                        INVENTREFTYPE = c.Int(nullable: false),
                        OPRID = c.String(),
                        ITEMID = c.String(),
                        SAVETYPE = c.Int(nullable: false),
                        X1VALUE = c.String(),
                        Y1VALUE = c.String(),
                        X2VALUE = c.String(),
                        Y2VALUE = c.String(),
                        GRAPHSIZEX = c.String(),
                        GRAPHSIZEY = c.String(),
                        CONVERTSCALEXPPB = c.Int(nullable: false),
                        CONVERTSCALEYPPB = c.Int(nullable: false),
                        CONVERTSCALEORTHOPPB = c.Int(nullable: false),
                        CONVERTDESIGNNAME = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        LICBUFFERSIZE1 = c.String(),
                        LAYERNAMEALIAS = c.String(),
                        CAMTOOL = c.String(),
                        EXPOSESIZEX = c.String(),
                        EXPOSESIZEY = c.String(),
                        MURAVALUE = c.String(),
                        Y_NOEXPOSESIZE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SDIST = c.Int(nullable: false),
                        GRAPHCD = c.String(),
                        GRAPHBIAS = c.String(),
                        DISTORTION = c.Int(nullable: false),
                        LARGESTLENGTH = c.Int(nullable: false),
                        TOTALLENGTH = c.Int(nullable: false),
                        LICUNITTIME = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PPO = c.Int(nullable: false),
                        AOITYPE = c.String(),
                        PARAMINDETERMINACY = c.Int(nullable: false),
                        XOR = c.Int(nullable: false),
                        ISSOURCEAOI = c.Int(nullable: false),
                        AOILAYER = c.String(),
                        AOITOPCELL = c.String(),
                        AOISOURCENAME = c.String(),
                        RESOULT = c.Int(),
                        Completion = c.Int(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CHECK_AOITABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        INVALID = c.Int(nullable: false),
                        PRODSERIAL = c.String(),
                        PRODID = c.String(),
                        AOIEQUIPMENT = c.String(),
                        AOIDIETODIE = c.Int(nullable: false),
                        AOIDIELOWSLOW = c.Int(nullable: false),
                        AOIDIELOWFAST = c.Int(nullable: false),
                        AOIDIESFAST = c.Int(nullable: false),
                        AOIDIEHIGHSLOW = c.Int(nullable: false),
                        AOIDIEHIGHFAST = c.Int(nullable: false),
                        AOIDIETRANS = c.Int(nullable: false),
                        AOIDIEREVER = c.Int(nullable: false),
                        AOIDIESHIELD1 = c.Int(nullable: false),
                        AOIDIESHIELD2 = c.Int(nullable: false),
                        AOIDIESHIELD3 = c.Int(nullable: false),
                        AOIDIESHIELD4 = c.Int(nullable: false),
                        AOIDIESTATO = c.String(),
                        AOIDIEFILENAME = c.String(),
                        AOIDIEBLACKBUGNUM = c.Int(nullable: false),
                        AOIDIEWHITEBUGNUM = c.Int(nullable: false),
                        AOIDIEDIRTHNUM = c.Int(nullable: false),
                        AOIDIETODIERESULT = c.String(),
                        AOIDIEOPERATOR = c.String(),
                        AOIDIETODB = c.Int(nullable: false),
                        AOIDBLOWSLOW = c.Int(nullable: false),
                        AOIDBLOWFAST = c.Int(nullable: false),
                        AOIDBHIGHSLOW = c.Int(nullable: false),
                        AOIDBHIGHFAST = c.Int(nullable: false),
                        AOIDBTRANS = c.Int(nullable: false),
                        AOIDBREVER = c.Int(nullable: false),
                        AOIDBV = c.String(),
                        AOIDBH = c.String(),
                        AOIDBCONVO = c.String(),
                        AOIDBREVERSE = c.Int(nullable: false),
                        AOIDBCORNERCUT = c.Int(nullable: false),
                        AOIDBHALFTONE = c.Int(nullable: false),
                        AOIDBSTATO = c.String(),
                        AOISCALEX = c.String(),
                        AOISCALEY = c.String(),
                        AOIDBSPEC = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AOIDBFILENAME = c.String(),
                        AOIDBBLACKBUGNUM = c.Int(nullable: false),
                        AOIDBWHITEBUGNUM = c.Int(nullable: false),
                        AOIDBDIRTHNUM = c.Int(nullable: false),
                        AOIDBTODIERESULT = c.String(),
                        AOIDBOPERATOR = c.String(),
                        AOIBUGTYPE1 = c.String(),
                        AOIBUGTYPE2 = c.String(),
                        AOIBUGTYPE3 = c.String(),
                        AOIBUGTYPE4 = c.String(),
                        AOIBUGTYPE5 = c.String(),
                        AOIBUGTYPE6 = c.String(),
                        AOIBUGTYPE7 = c.String(),
                        AOIBUGTYPE8 = c.String(),
                        AOIOPERATETIME = c.DateTime(nullable: false),
                        AOIOPERATETIMETZID = c.Int(nullable: false),
                        AOIBUGPOSX1 = c.String(),
                        AOIBUGPOSX2 = c.String(),
                        AOIBUGPOSX3 = c.String(),
                        AOIBUGPOSX4 = c.String(),
                        AOIBUGPOSX5 = c.String(),
                        AOIBUGPOSX6 = c.String(),
                        AOIBUGPOSX7 = c.String(),
                        AOIBUGPOSX8 = c.String(),
                        AOIBUGPOSSIZE1 = c.String(),
                        AOIBUGPOSSIZE2 = c.String(),
                        AOIBUGPOSSIZE3 = c.String(),
                        AOIBUGPOSSIZE4 = c.String(),
                        AOIBUGPOSSIZE5 = c.String(),
                        AOIBUGPOSSIZE6 = c.String(),
                        AOIBUGPOSSIZE7 = c.String(),
                        AOIBUGPOSSIZE8 = c.String(),
                        AOIBUGPOSY1 = c.String(),
                        AOIBUGPOSY2 = c.String(),
                        AOIBUGPOSY3 = c.String(),
                        AOIBUGPOSY4 = c.String(),
                        AOIBUGPOSY5 = c.String(),
                        AOIBUGPOSY6 = c.String(),
                        AOIBUGPOSY7 = c.String(),
                        AOIBUGPOSY8 = c.String(),
                        OPRID = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        MODIFIEDDATETIME = c.DateTime(nullable: false),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        MODIFIEDBY = c.String(),
                        CREATEDBY = c.String(),
                        OPRNAME = c.String(),
                        ISSHIPMENTREPORT = c.Int(nullable: false),
                        ZAPOPERATOR = c.String(),
                        CVDOPERATOR = c.String(),
                        AOIWRKCTRNAME = c.String(),
                        AOIEQUIPMENT1 = c.String(),
                        AOIEQUIPMENT2 = c.String(),
                        AOIEQUIPMENT3 = c.String(),
                        AOIWRKCTRNAME1 = c.String(),
                        AOIWRKCTRNAME2 = c.String(),
                        AOIWRKCTRNAME3 = c.String(),
                        AOIBLACKBUGNUM1 = c.Int(nullable: false),
                        AOIWHITEBUGNUM1 = c.Int(nullable: false),
                        AOIWHITEBUGNUM2 = c.Int(nullable: false),
                        AOIBLACKBUGNUM2 = c.Int(nullable: false),
                        AOIWHITEBUGNUM3 = c.Int(nullable: false),
                        AOIBLACKBUGNUM3 = c.Int(nullable: false),
                        AOIWHITEBUGNUM4 = c.Int(nullable: false),
                        AOIBLACKBUGNUM4 = c.Int(nullable: false),
                        ISCHECKBYAREA = c.Int(nullable: false),
                        Completion = c.Int(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CHECK_INNERPACKTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        PACKBOXSIZE = c.Int(nullable: false),
                        PACKBOXCLEANYES = c.Int(nullable: false),
                        PACKBOXCLEANNO = c.Int(nullable: false),
                        PACKBOXSTATICYES = c.Int(nullable: false),
                        PACKBOXSTATICNO = c.Int(nullable: false),
                        PACKMETHOD = c.String(),
                        PACKOPERATOR1 = c.String(),
                        PACKOPERATOR2 = c.String(),
                        PACKOPERATOR3 = c.String(),
                        PACKRESULT = c.Int(nullable: false),
                        PACKREMARKS = c.String(),
                        PACKTIME = c.DateTime(nullable: false),
                        PACKTIMETZID = c.Int(nullable: false),
                        FQCCUSTOMER = c.String(),
                        FQCMASKTITLE = c.String(),
                        FQCLAYERNAME = c.String(),
                        FQCMASKSIZE = c.String(),
                        FQCMATERIAL = c.String(),
                        FQCSUPERMASKLOT = c.String(),
                        SHIPCUSTOMER = c.String(),
                        SHIPMASKSIZE = c.String(),
                        SHIPMATERIAL = c.String(),
                        SHIPQTY = c.String(),
                        SHIPNO = c.String(),
                        SHIPCARTONNO = c.String(),
                        FQCDATE = c.String(),
                        SHIPDATE = c.String(),
                        INVALID = c.Int(nullable: false),
                        PRODSERIAL = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        MODIFIEDDATETIME = c.DateTime(nullable: false),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        MODIFIEDBY = c.String(),
                        CREATEDBY = c.String(),
                        ISSHIPMENTREPORT = c.Int(nullable: false),
                        PACKFOGNUM = c.Int(nullable: false),
                        PACKBUTTNUM = c.Int(nullable: false),
                        PACKCORNERNUM = c.Int(nullable: false),
                        PACKDESTROYNUM = c.Int(nullable: false),
                        PACKLINENUM = c.Int(nullable: false),
                        PACKBOXMATERIALNO = c.String(),
                        PACKBOXMATERIALBATCHNO = c.String(),
                        PACKBOXUSENUM = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QUALITYRESULT = c.String(),
                        ISSTRIPE6 = c.String(),
                        ISSTRIPE5 = c.String(),
                        ISSTRIPE4 = c.String(),
                        ISSTRIPE3 = c.String(),
                        ISSTRIPE2 = c.String(),
                        ISSTRIPE1 = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CHECK_LONGSIZETABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        LONGCENTERTOLE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNX12 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNX22 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNY12 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNY22 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKX12 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKX22 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKY12 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKY22 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEX12 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEX22 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEY12 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEY22 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZECODE = c.String(),
                        LONGSIZERESULT = c.String(),
                        LONGOPERATETIME = c.DateTime(nullable: false),
                        LONGOPERATETIMETZID = c.Int(nullable: false),
                        LONGREMARKS = c.String(),
                        INVALID = c.Int(nullable: false),
                        PRODSERIAL = c.String(),
                        OPRID = c.String(),
                        LONGSIZEDESIGNX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZEDESIGNX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZEDESIGNY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZEDESIGNY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZECHECKX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZECHECKX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZECHECKY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZECHECKY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZETOLEX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZETOLEX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZETOLEY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGSIZETOLEY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        LONGSIZETOLE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MODIFIEDDATETIME = c.DateTime(nullable: false),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        MODIFIEDBY = c.String(),
                        CREATEDBY = c.String(),
                        LONGCENTERDESIGNG = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERDESIGNH = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKG = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERCHECKH = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEG = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LONGCENTERTOLEH = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ISSHIPMENTREPORT = c.Int(nullable: false),
                        ISLONGCENTERDESIGNADD = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CHECK_PELLICLETABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        PRODSERIAL = c.String(),
                        INVALID = c.Int(nullable: false),
                        GUIDESPEC = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEDESIGN = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEMEASUREX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEMEASUREX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEMEASUREY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEMEASUREY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEERRORX1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEERRORX2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEERRORY1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEERRORY2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PELLICLEMATERIALNO1 = c.String(),
                        PELLICLEBATCHNO1 = c.String(),
                        PELLICLEUSENUM1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PELLICLEMATERIALNO2 = c.String(),
                        PELLICLEBATCHNO2 = c.String(),
                        PELLICLEUSENUM2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PELLICLEOPERATOR = c.String(),
                        PELLICLEOPTIME = c.DateTime(nullable: false),
                        PELLICLEOPTIMETZID = c.Int(nullable: false),
                        GUIDEOPERATOR = c.String(),
                        GUIDEOPTIME = c.DateTime(nullable: false),
                        GUIDEOPTIMETZID = c.Int(nullable: false),
                        OPRID = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        PELLICLEMATRIALTYPE1 = c.String(),
                        PELLICLEMATRIALTYPE2 = c.String(),
                        MODIFIEDDATETIME = c.DateTime(nullable: false),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        MODIFIEDBY = c.String(),
                        CREATEDBY = c.String(),
                        ISSHIPMENTREPORT = c.Int(nullable: false),
                        PELLICLEOPERATOR1 = c.String(),
                        PELLICLEOPERATOR2 = c.String(),
                        PELLICLEOPERATOR3 = c.String(),
                        PELLICLEREMARKS = c.String(),
                        ISPELLICLEDISPOSED1 = c.Int(nullable: false),
                        ISPELLICLEDISPOSED2 = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CHECK_REPAIRTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        REPAIRZAPBLACKNUM = c.Int(nullable: false),
                        REPAIRZAPBURRNUM = c.Int(nullable: false),
                        REPAIRZAPLINKNUM = c.Int(nullable: false),
                        REPAIRZAPTOTALNUM = c.Int(nullable: false),
                        REPAIRZAPRBLACKNUM = c.Int(nullable: false),
                        REPAIRZAPRBURRNUM = c.Int(nullable: false),
                        REPAIRZAPRLINKNUM = c.Int(nullable: false),
                        REPAIRZAPRTOTALNUM = c.Int(nullable: false),
                        REPAIRZAPBUGID = c.Int(nullable: false),
                        REPAIRZAPCRAFTNAME = c.String(),
                        REPAIRZAPPICNAME = c.String(),
                        REPAIRZAPOTHERS = c.String(),
                        REPAIRCVDTRY = c.String(),
                        REPAIRCVDHOLENUM = c.Int(nullable: false),
                        REPAIRCVDHOLLOWNUM = c.Int(nullable: false),
                        REPAIRCVDCUTNUM = c.Int(nullable: false),
                        REPAIRCVDTOTALNUM = c.Int(nullable: false),
                        REPAIRCVDRHOLENUM = c.Int(nullable: false),
                        REPAIRCVDRHOLLOWNUM = c.Int(nullable: false),
                        REPAIRCVDRCUTNUM = c.Int(nullable: false),
                        REPAIRCVDRTOTALNUM = c.Int(nullable: false),
                        REPAIRCVDBUGID = c.Int(nullable: false),
                        REPAIRCVDCRAFTNAME = c.String(),
                        REPAIRCVDPICNAME = c.String(),
                        REPAIRCVDOTHERS = c.String(),
                        REPAIRDOZAP = c.String(),
                        REPAIRDOZAPREMARKS = c.String(),
                        REPAIRCVDPHOTIC = c.String(),
                        REPAIRSURFACE = c.String(),
                        REPAIRCONFIRM = c.String(),
                        REPAIRBUGTYPE = c.String(),
                        REPAIRBUGNO = c.String(),
                        REPAIRTYPE = c.String(),
                        REPAIRSURFACERE = c.String(),
                        REPAIRCONFIRMRE = c.String(),
                        REPAIRBLACKTOTALNUM = c.Int(nullable: false),
                        REPAIRBURRTOTALNUM = c.Int(nullable: false),
                        REPAIRLINKTOTALNUM = c.Int(nullable: false),
                        REPAIRHOLETOTALNUM = c.Int(nullable: false),
                        REPAIRHOLLOWTOTALNUM = c.Int(nullable: false),
                        REPAIRCUTTOTALNUM = c.Int(nullable: false),
                        REPAIRZAPOK1 = c.Int(nullable: false),
                        REPAIRZAPOK2 = c.Int(nullable: false),
                        REPAIRZAPOK3 = c.Int(nullable: false),
                        REPAIRZAPOK4 = c.Int(nullable: false),
                        REPAIRZAPOK5 = c.Int(nullable: false),
                        REPAIRZAPOK6 = c.Int(nullable: false),
                        REPAIRZAPOK7 = c.Int(nullable: false),
                        REPAIRZAPOK8 = c.Int(nullable: false),
                        REPAIRSURFACEOK = c.Int(nullable: false),
                        REPAIRCONFIRMOK = c.Int(nullable: false),
                        REPAIRREOK1 = c.Int(nullable: false),
                        REPAIRREOK2 = c.Int(nullable: false),
                        REPAIRREOK3 = c.Int(nullable: false),
                        REPAIRREOK4 = c.Int(nullable: false),
                        REPAIRREOK5 = c.Int(nullable: false),
                        REPAIRBUGTOTALNUMOK = c.Int(nullable: false),
                        REPAIROPERATOR = c.String(),
                        REPAIRTIME = c.DateTime(nullable: false),
                        REPAIRTIMETZID = c.Int(nullable: false),
                        INVALID = c.Int(nullable: false),
                        PRODSERIAL = c.String(),
                        OPRID = c.String(),
                        REPAIRINK = c.String(),
                        REPAIRLCVD = c.String(),
                        REPAIRAFILM = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        MODIFIEDDATETIME = c.DateTime(nullable: false),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        MODIFIEDBY = c.String(),
                        CREATEDBY = c.String(),
                        ISSHIPMENTREPORT = c.Int(nullable: false),
                        ZAPOPERATOR = c.String(),
                        CVDOPERATOR = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CHECK_WASHTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        RECID = c.Long(nullable: false),
                        MRECIPENAME = c.String(),
                        JRECIPENAME = c.String(),
                        RESULT = c.Byte(nullable: false),
                        OPERATOR = c.String(),
                        BENGBIAN = c.Int(nullable: false),
                        BENGJIAO = c.Int(nullable: false),
                        HUASHANG = c.Int(nullable: false),
                        LIEWEN = c.Int(nullable: false),
                        DIRTYPOINT = c.Int(nullable: false),
                        STREAK = c.Int(nullable: false),
                        UNUSUALMESSAGE = c.String(),
                        STARTTIME = c.DateTime(nullable: false),
                        ENDTIME = c.DateTime(nullable: false),
                        TIMESNUM = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_CUSTPARATRADETABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        CUSTTRADEREPORTAREA = c.Int(nullable: false),
                        CUSTTRADEREPORTTYPE = c.Int(nullable: false),
                        MEASUREREPORT = c.Int(nullable: false),
                        MAKEOUTDEFECT = c.Int(nullable: false),
                        BARCODE = c.Int(nullable: false),
                        LABLE = c.Int(nullable: false),
                        LABLETYPE = c.Int(nullable: false),
                        DEFECTTYPE = c.Int(nullable: false),
                        CUSTTRADEREPORTADDRESS = c.Int(nullable: false),
                        SPECIALDESC = c.String(),
                        DELIVERTYPE = c.Int(nullable: false),
                        DELEVEROTHERDESC = c.String(),
                        DELIVERYDOC = c.Int(nullable: false),
                        LOGISTICALDOC = c.Int(nullable: false),
                        LOGISTICALOTHERDESC = c.String(),
                        MAKEUPORDERNUM = c.Int(nullable: false),
                        PRINTPRICE = c.Int(nullable: false),
                        ROHS = c.Int(nullable: false),
                        DELIVERYDOCOTHER = c.Int(nullable: false),
                        DELIVERYDOCOTHERDESC = c.String(),
                        WASHWAY = c.String(),
                        TUXINGYAOQIU = c.Int(nullable: false),
                        KEHUBAOGUANGJIMODEL = c.String(),
                        BAOGUANGWENDU = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PACKINGDEMANDINNER = c.Int(nullable: false),
                        JIECHUSHIBAOZHTYPE = c.Int(nullable: false),
                        XIAOBANJINGHUATYPE = c.Int(nullable: false),
                        JIAODAIMIFENG = c.Int(nullable: false),
                        JIAODAIYOUWU = c.Int(nullable: false),
                        JINGHUADAI = c.Int(nullable: false),
                        JINGHUADAITYPE = c.Int(nullable: false),
                        LEIXING = c.Int(nullable: false),
                        FENGZHLEIX = c.Int(nullable: false),
                        FENGZHOTHER = c.Int(nullable: false),
                        FENGZHOTHERDESC = c.String(),
                        PACKINGDEMANDOUTER = c.Int(nullable: false),
                        BIAOMINGZHMXH = c.Int(nullable: false),
                        BIAOMIANTZH = c.Int(nullable: false),
                        YAOQIUOTHER = c.Int(nullable: false),
                        YAOQIUOTHERDESC = c.String(),
                        ITEMID = c.String(),
                        CUSTACCOUNT = c.String(),
                        ICSHIPPINGREPORT = c.Int(nullable: false),
                        OTHERREPORT = c.Int(nullable: false),
                        PRINTREMAND = c.Int(nullable: false),
                        OTHERREPORTVALUE = c.String(),
                        BIGVERSIONBOX = c.Int(nullable: false),
                        RETICLEABS = c.Int(nullable: false),
                        NOTRETICLEABS = c.Int(nullable: false),
                        PPBOXCHINA = c.Int(nullable: false),
                        PPBOXFOREIGN = c.Int(nullable: false),
                        ENVIRREQ = c.Int(nullable: false),
                        CLEANPACKAGESINGLE = c.Int(nullable: false),
                        CLEANPACKAGEDOUBLE = c.Int(nullable: false),
                        MANUALFILMPACKAGE = c.Int(nullable: false),
                        PACKAGECLEANREQ = c.Int(nullable: false),
                        VACUUMPACKAGE = c.Int(nullable: false),
                        FILMMACHINEPACKAGE = c.Int(nullable: false),
                        OTHERPACKAGE = c.Int(nullable: false),
                        OTHERPACKAGEVALUE = c.String(),
                        C5DELIVERYREPORT = c.Int(nullable: false),
                        DELIVERYSPECIALDESC = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        ICSHIPPINGREPORTCOM = c.Int(nullable: false),
                        QY_ISPACKBOXSUPPORTOR = c.Int(nullable: false),
                        QY_PB_GUDENG = c.Int(nullable: false),
                        QY_PB_SEYANG = c.Int(nullable: false),
                        QY_PB_POZZETTA = c.Int(nullable: false),
                        QY_PB_GUOHUA = c.Int(nullable: false),
                        QY_PB_KEHU = c.Int(nullable: false),
                        QY_PB_OTHERS = c.Int(nullable: false),
                        QY_PB_OTHERSVALUE = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_JINGDUQUEXIANPARAMETER",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        ITEMID = c.String(),
                        XFLESS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        XFRANGE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        XFMORE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CUSTACCOUNT = c.String(),
                        XFLESSMATHSYMBOL = c.Int(nullable: false),
                        XFGREATERMATHSYMBOL = c.Int(nullable: false),
                        XIANFENGOTHER = c.Int(nullable: false),
                        XIANFENGOTHERVALUE = c.String(),
                        XIANFENG = c.Int(nullable: false),
                        TAOHE = c.Int(nullable: false),
                        TAOHEOTHER = c.Int(nullable: false),
                        TAOHEOTHERVALUE = c.String(),
                        THVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        THRANGE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ZONGCHANG = c.Int(nullable: false),
                        ZONGCHANGOTHER = c.Int(nullable: false),
                        ZONGCHANGOTHERVALUE = c.String(),
                        ZONGCHANGVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ZONGCHANGRANGE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CHUIZHIDU = c.Int(nullable: false),
                        CHUIZHIDUOTHER = c.Int(nullable: false),
                        CHUIZHIDUOTHERVALUE = c.String(),
                        CHUIZHIDUVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CHUIZHIDURANGE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QXDYAREA = c.String(),
                        QXDYAREAF = c.String(),
                        BUYUNXUCHAOCU = c.Int(nullable: false),
                        BUYUNXUCHAOCUF = c.Int(nullable: false),
                        TESUYAOQIU = c.String(),
                        TESUYAOQIUF = c.String(),
                        CHANPINYAOQIU = c.Int(nullable: false),
                        CHANPINYAOQIUVALUE = c.String(),
                        MAOCIXIUBUVALUE = c.String(),
                        MAOCIXIUBU = c.Int(nullable: false),
                        ZHENKONGAOXIANSHULIANG = c.Int(nullable: false),
                        ZHENKONGAOXIANSHULIANGVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ZHENKONGAOXIANGAODU = c.Int(nullable: false),
                        ZHENKONGAOXIANGAODUVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QITACAILIAO = c.Int(nullable: false),
                        QITACAILIAOVALUE = c.String(),
                        JINSHUYE = c.Int(nullable: false),
                        YOUMO = c.Int(nullable: false),
                        HONGTU = c.Int(nullable: false),
                        AXINGJIAO = c.Int(nullable: false),
                        LCVD = c.Int(nullable: false),
                        XIANTIAOZHILIANG = c.Int(nullable: false),
                        XIANTIAOZHILIANGVALUE = c.String(),
                        ZHENGBANTIAOWENVALUE = c.String(),
                        ZHENGBANTIAOWEN = c.Int(nullable: false),
                        ZHENYUANDU = c.Int(nullable: false),
                        ZHENYUANDUVALUE = c.String(),
                        XIANFENGCELIANGVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CHANGCHICUNCELIANG = c.Int(nullable: false),
                        CHANGCHICUNCELIANGVALUE = c.String(),
                        SHUJUFENXIYAOQIU = c.Int(nullable: false),
                        SHUJUFENXIYAOQIUVALUE = c.String(),
                        COPYOFCHANPINYAOQIUVALUE = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        MAXBUGSIZE = c.Decimal(nullable: false, precision: 18, scale: 2),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IWS_PRODUCTPARAMETER",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        ITEMID = c.String(),
                        BANCAITYPE = c.Int(nullable: false),
                        BANCAIDESC = c.String(),
                        SIZE1X = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SIZE1Y = c.Decimal(nullable: false, precision: 18, scale: 2),
                        HOU11 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        WUCHATYPE = c.Int(nullable: false),
                        PINGZHENGDUYAOQIU = c.Int(nullable: false),
                        PINGZHENGDUYAOQIUDESC = c.String(),
                        QIEGEJINGDU = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DAOJIAOYAOQIU = c.Int(nullable: false),
                        DAOJIAOSIZE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BENGBIANYAOQIU = c.Int(nullable: false),
                        BENGBIANOTHERVALUE = c.String(),
                        WUCHAVALUE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PELLICLEYAOQIU = c.Int(nullable: false),
                        PELLICLEYAOQIUTYPE = c.Int(nullable: false),
                        PELLICLEMODEL = c.String(),
                        PELLICLEJINGDU = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GUIDEYAOQIU = c.Int(nullable: false),
                        GUIDETIEHETPYE = c.Int(nullable: false),
                        CUSTACCOUNT = c.String(),
                        JUZHONGYAOQIU = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SECTIONALQUALITYVALUE = c.String(),
                        SECTIONALQUALITY = c.Int(nullable: false),
                        SCRATCH = c.String(),
                        CUSTCLEANWAY = c.String(),
                        OUTSIDESTAIN = c.String(),
                        DAOJIAOSIZEVALUE = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.PRODBOM",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        LINENUM = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PRODLINETYPE = c.Int(nullable: false),
                        BOMCONSUMP = c.Int(nullable: false),
                        ITEMID = c.String(),
                        BOMQTY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIM1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIM2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIM3 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIM4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIM5 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ROUNDUP = c.Int(nullable: false),
                        ROUNDUPQTY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        POSITION = c.String(),
                        QTYBOMCALC = c.Decimal(nullable: false, precision: 18, scale: 2),
                        REMAINBOMPHYSICAL = c.Decimal(nullable: false, precision: 18, scale: 2),
                        REMAINBOMFINANCIAL = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QTYINVENTCALC = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PRODFLUSHINGPRINCIP = c.Int(nullable: false),
                        RESERVATION = c.Int(nullable: false),
                        INVENTTRANSID = c.String(),
                        RAWMATERIALDATE = c.DateTime(nullable: false),
                        REMAININVENTPHYSICAL = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIMENSION = c.String(),
                        DIMENSION2_ = c.String(),
                        DIMENSION3_ = c.String(),
                        INVENTREFTYPE = c.Int(nullable: false),
                        INVENTREFID = c.String(),
                        INVENTREFTRANSID = c.String(),
                        VENDID = c.String(),
                        UNITID = c.String(),
                        BACKORDERSTATUS = c.Int(nullable: false),
                        CALCULATION = c.Int(nullable: false),
                        QTYINVENTSTUP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QTYBOMSTUP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BOMID = c.String(),
                        FORMULA = c.Int(nullable: false),
                        BOMREFRECID = c.Long(nullable: false),
                        BOMQTYSERIE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ITEMBOMID = c.String(),
                        INVENTDIMID = c.String(),
                        REQPOID = c.String(),
                        REQPLANIDSCHED = c.String(),
                        SCRAPVAR = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SCRAPCONST = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CONSTANTRELEASED = c.Int(nullable: false),
                        ENDCONSUMP = c.Int(nullable: false),
                        PROJCATEGORYID = c.String(),
                        ACTIVITYNUMBER = c.String(),
                        PROJTRANSID = c.String(),
                        PROJTRANSDATE = c.DateTime(nullable: false),
                        PROJLINEPROPERTYID = c.String(),
                        PROJCOSTPRICE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROJCOSTAMOUNT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROJSALESCURRENCYID = c.String(),
                        PROJSALESPRICE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROJTAXGROUPID = c.String(),
                        PROJTAXITEMGROUPID = c.String(),
                        PROJID = c.String(),
                        PROJSETSUBPRODTOCONSUMED = c.Int(nullable: false),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        OPRNUM = c.Int(nullable: false),
                        WRKCTRCONSUMPTION = c.Int(nullable: false),
                        ITEMROUTEID = c.String(),
                        RAWMATERIALTIME = c.Int(nullable: false),
                        ENDSCHEDCONSUMP = c.Int(nullable: false),
                        IWS_REPLACEITEMID = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.PRODJOURNALBOM",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        JOURNALID = c.String(),
                        VOUCHER = c.String(),
                        LINENUM = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PRODID = c.String(),
                        TRANSDATE = c.DateTime(nullable: false),
                        ITEMID = c.String(),
                        PROJID = c.String(),
                        INVENTTRANSID = c.String(),
                        POSITION = c.String(),
                        INVENTCONSUMP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BOMCONSUMP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BOMUNITID = c.String(),
                        INVENTPROPOSAL = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BOMPROPOSAL = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BOMSCRAP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ERRORCAUSE = c.Int(nullable: false),
                        DIMENSION = c.String(),
                        DIMENSION2_ = c.String(),
                        DIMENSION3_ = c.String(),
                        ENDCONSUMP = c.Int(nullable: false),
                        INVENTDIMID = c.String(),
                        INVENTTRANSCHILDREFID = c.String(),
                        INVENTTRANSCHILDTYPE = c.Int(nullable: false),
                        INVENTRETURNFLAG = c.Int(nullable: false),
                        INVENTCONTROLPROPOSAL = c.Int(nullable: false),
                        ACTIVITYNUMBER = c.String(),
                        PROJCATEGORYID = c.String(),
                        PROJLINEPROPERTYID = c.String(),
                        PROJTRANSID = c.String(),
                        PROJCOSTPRICE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROJCOSTAMOUNT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROJSALESCURRENCYID = c.String(),
                        PROJSALESPRICE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROJTAXGROUPID = c.String(),
                        PROJTAXITEMGROUPID = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        OPRNUM = c.Int(nullable: false),
                        IWS_INVENTSERIALID = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.PRODJOURNALROUTE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        JOURNALID = c.String(),
                        VOUCHER = c.String(),
                        LINENUM = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TRANSDATE = c.DateTime(nullable: false),
                        PRODID = c.String(),
                        WRKCTRID = c.String(),
                        HOURPRICE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QTYGOOD = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QTYERROR = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ERRORCAUSE = c.Int(nullable: false),
                        EMPLID = c.String(),
                        DIMENSION = c.String(),
                        DIMENSION2_ = c.String(),
                        DIMENSION3_ = c.String(),
                        CANCELLED = c.Int(nullable: false),
                        PRODINVENTDIMID = c.String(),
                        PRODPICKLISTJOURNALID = c.String(),
                        PRODREPORTFINISHEDJOURNALID = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        OPRNUM = c.Int(nullable: false),
                        JOBTYPE = c.Int(nullable: false),
                        HOURS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CATEGORYHOURSID = c.String(),
                        QTYPRICE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        OPRFINISHED = c.Int(nullable: false),
                        CATEGORYQTYID = c.String(),
                        EXECUTEDPCT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        JOBFINISHED = c.Int(nullable: false),
                        OPRPRIORITY = c.Int(nullable: false),
                        FROMTIME = c.Int(nullable: false),
                        TOTIME = c.Int(nullable: false),
                        JOBID = c.String(),
                        OPRID = c.String(),
                        PRODREPORTFINISHED = c.Int(nullable: false),
                        PRODPICKLIST = c.Int(nullable: false),
                        IWS_WRKSTATUS = c.Int(nullable: false),
                        IWS_HOURS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_IPCAMOUNT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_SHEETGOOD = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_SHEETERROR = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_WEIGHTS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_EMPLNAME = c.String(),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        QY_MINUTE = c.Decimal(nullable: false, precision: 18, scale: 2),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.PRODROUTE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        PRODID = c.String(),
                        OPRNUM = c.Int(nullable: false),
                        LEVEL_ = c.Int(nullable: false),
                        OPRNUMNEXT = c.Int(nullable: false),
                        OPRID = c.String(),
                        WRKCTRID = c.String(),
                        TASKGROUPID = c.String(),
                        QUEUETIMEBEFORE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SETUPTIME = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROCESSTIME = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROCESSPERQTY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TRANSPTIME = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QUEUETIMEAFTER = c.Decimal(nullable: false, precision: 18, scale: 2),
                        OVERLAPQTY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ERRORPCT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ACCERROR = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TOHOURS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TRANSFERBATCH = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SETUPCATEGORYID = c.String(),
                        PROCESSCATEGORYID = c.String(),
                        OPRFINISHED = c.Int(nullable: false),
                        FORMULAFACTOR1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ROUTETYPE = c.Int(nullable: false),
                        BACKORDERSTATUS = c.Int(nullable: false),
                        PROPERTYID = c.String(),
                        ROUTEGROUPID = c.String(),
                        QTYCATEGORYID = c.String(),
                        FROMDATE = c.DateTime(nullable: false),
                        FROMTIME = c.Int(nullable: false),
                        TODATE = c.DateTime(nullable: false),
                        TOTIME = c.Int(nullable: false),
                        CALCQTY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CALCSETUP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CALCPROC = c.Decimal(nullable: false, precision: 18, scale: 2),
                        WRKCTRTASKDEMAND = c.Decimal(nullable: false, precision: 18, scale: 2),
                        OPRPRIORITY = c.Int(nullable: false),
                        WRKCTRLOADPCT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        WRKCTRNUMOF = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIMENSION = c.String(),
                        DIMENSION2_ = c.String(),
                        DIMENSION3_ = c.String(),
                        FORMULA = c.Int(nullable: false),
                        ROUTEOPRREFRECID = c.Long(nullable: false),
                        LINKTYPE = c.Int(nullable: false),
                        OPRSTARTEDUP = c.Int(nullable: false),
                        EXECUTEDPROCESS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        EXECUTEDSETUP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CONSTANTRELEASED = c.Int(nullable: false),
                        PHANTOMBOMFACTOR = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        IWS_COSTCATEGORYGROUPID = c.String(),
                        IWS_TIMECATEGORYGROUPID = c.String(),
                        QY_OPRLEVEL = c.Int(nullable: false),
                        QY_FROMDATETIME = c.DateTime(nullable: false),
                        QY_FROMDATETIMETZID = c.Int(nullable: false),
                        QY_TODATETIME = c.DateTime(nullable: false),
                        QY_TODATETIMETZID = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.PRODTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        ITEMID = c.String(),
                        NAME = c.String(),
                        PRODSTATUS = c.Int(nullable: false),
                        DATAAREAID = c.String(),
                        PRODPRIO = c.Int(nullable: false),
                        PRODLOCKED = c.Int(nullable: false),
                        PRODTYPE = c.Int(nullable: false),
                        SCHEDSTATUS = c.Int(nullable: false),
                        SCHEDDATE = c.DateTime(nullable: false),
                        QTYSCHED = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QTYSTUP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DLVDATE = c.DateTime(nullable: false),
                        FINISHEDDATE = c.DateTime(nullable: false),
                        SCHEDSTART = c.DateTime(nullable: false),
                        SCHEDEND = c.DateTime(nullable: false),
                        INVENTTRANSID = c.String(),
                        DIMENSION = c.String(),
                        DIMENSION2_ = c.String(),
                        BOMDATE = c.DateTime(nullable: false),
                        BACKORDERSTATUS = c.Int(nullable: false),
                        BOMID = c.String(),
                        ROUTEID = c.String(),
                        PRODID = c.String(),
                        REALTIMEOPRID = c.String(),
                        INVENTDIMID = c.String(),
                        DLVTIME = c.Int(nullable: false),
                        IWS_WRKCTRID = c.String(),
                        IWS_SCRAPRESEND = c.Int(nullable: false),
                        IWS_PRODUCTIONTYPE = c.Int(nullable: false),
                        IWS_LINETYPE = c.Int(nullable: false),
                        IWS_ISSUSPEND = c.Int(nullable: false),
                        IWS_DIAODUDATETIME = c.DateTime(nullable: false),
                        IWS_DIAODUDATETIMETZID = c.Int(nullable: false),
                        IWS_OTHERREQUEST = c.String(),
                        IWS_MATERIALREMARKS = c.String(),
                        IWS_DIAODUSHIREMARKS = c.String(),
                        IWS_DESIGNREAMRKS = c.String(),
                        IWS_ISNEWPRODUCTION = c.Int(nullable: false),
                        IWS_TOTALLENGTH = c.Int(nullable: false),
                        IWS_MINLINEWIDTHINMARKET = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_SALESNAME = c.String(),
                        IWS_MODELNUMBER = c.String(),
                        IWS_ITEMMIDDLETYPENAME = c.String(),
                        IWS_CDACCURACY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_LINEWIDEFROM = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SHIPPINGDATEREQUESTED = c.DateTime(nullable: false),
                        IWS_SPECIFICATIONS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_SPECIFICATIONS2_ = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_SPECIFICATIONS3_ = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IWS_CUSTNAMESEND = c.String(),
                        IWS_MARKETREMARKS = c.String(),
                        SALESID = c.String(),
                        IWS_SALESORDERDATE = c.DateTime(nullable: false),
                        IWS_SALESORDERDATETZID = c.Int(nullable: false),
                        IWS_BANBIANXIAOGUO = c.String(),
                        IWS_TUXINGJUBIAN = c.String(),
                        IWS_TUXINGTEZENG = c.String(),
                        IWS_BANCAITYPENAME = c.String(),
                        IWS_SUPERVISETYPE = c.Int(nullable: false),
                        IWS_EXAMBILLSREMARK = c.String(),
                        IWS_WRKCTRGRP = c.String(),
                        IWS_PLANDLVFLAG = c.Int(nullable: false),
                        IWS_CRAFTREMARKS = c.String(),
                        MODIFIEDBY = c.String(),
                        MODIFIEDTRANSACTIONID = c.String(),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        CREATEDBY = c.String(),
                        QY_ISCAMNEEDEDAOI = c.Int(nullable: false),
                        AOICREATEDDATETIME = c.DateTime(nullable: false),
                        AOICREATEDDATETIMETZID = c.Int(nullable: false),
                        QY_PREPUTINDATE = c.DateTime(nullable: false),
                        QY_PREPUTINDATETZID = c.Int(nullable: false),
                        QY_PREEXPOSEDATE = c.DateTime(nullable: false),
                        QY_PREEXPOSEDATETZID = c.Int(nullable: false),
                        PROCESS = c.Int(),
                        ISSTARTED = c.Int(),
                        STARTDATE = c.DateTime(),
                        DUEDATE = c.DateTime(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.QY_CHECK_CDTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Num = c.String(),
                        CHECKDATA = c.String(),
                        COORDINATEY = c.String(),
                        COORDINATEX = c.String(),
                        SPEC = c.String(),
                        LINETYPE = c.String(),
                        CDTYPE = c.String(),
                        METHOD = c.String(),
                        DESIGN = c.String(),
                        GROUPID = c.Int(nullable: false),
                        PRODID = c.String(),
                        PRODSERIAL = c.String(),
                        INVALID = c.Int(nullable: false),
                        OPRID = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.QY_CHECK_TPTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        DEVY = c.String(),
                        DEVX = c.String(),
                        NOMY = c.String(),
                        NOMX = c.String(),
                        ZCORRECTION = c.String(),
                        ORTHO = c.String(),
                        YSCALE = c.String(),
                        XSCALE = c.String(),
                        OPRID = c.String(),
                        INVALID = c.Int(nullable: false),
                        PRODSERIAL = c.String(),
                        PRODID = c.String(),
                        CREATEDDATETIME = c.DateTime(nullable: false),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.ROUTEOPRTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        OPRID = c.String(),
                        NAME = c.String(),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(),
                        RECID = c.Long(),
                        IWS_PRODSHOW = c.Int(),
                        IWS_ROUTEOPRTYPE = c.Int(),
                        IWS_ROUTEOPRNUM = c.Int(),
                        IWS_ADDITIONALOPRID = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.WRKCTRTABLE",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        WRKCTRGROUPID = c.String(),
                        WRKCTRID = c.String(),
                        NAME = c.String(),
                        WRKCTRTYPE = c.Int(nullable: false),
                        WRKCTRNUMOF = c.Decimal(nullable: false, precision: 18, scale: 2),
                        EFFECTIVITYPCT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        OPERATIONSCHEDPCT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CAPACITY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CAPUNIT = c.Int(nullable: false),
                        VENDID = c.String(),
                        CREATED = c.DateTime(nullable: false),
                        TOHOURS = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DIMENSION = c.String(),
                        DIMENSION2_ = c.String(),
                        DIMENSION3_ = c.String(),
                        ISGROUP = c.Int(nullable: false),
                        PRODUNITID = c.String(),
                        SITEID = c.String(),
                        BOTTLENECKRESOURCE = c.Int(nullable: false),
                        WMSLOCATIONID = c.String(),
                        EMPLID = c.String(),
                        CALENDARID = c.String(),
                        CAPLIMITED = c.Int(nullable: false),
                        INVENTLOCATIONID = c.String(),
                        CAPACITYBATCH = c.Decimal(nullable: false, precision: 18, scale: 2),
                        EXCLUSIVE = c.Int(nullable: false),
                        DATAAREAID = c.String(),
                        RECVERSION = c.Int(nullable: false),
                        RECID = c.Long(nullable: false),
                        ACCOUNTWRKCTRISSUE = c.String(),
                        ACCOUNTWIPVALUATION = c.String(),
                        QUEUETIMEBEFORE = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SETUPTIME = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROCESSTIME = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROCESSPERQTY = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TRANSPTIME = c.Decimal(nullable: false, precision: 18, scale: 2),
                        QUEUETIMEAFTER = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TRANSFERBATCH = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ERRORPCT = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SETUPCATEGORYID = c.String(),
                        PROCESSCATEGORYID = c.String(),
                        ACCOUNTWIPISSUE = c.String(),
                        TASKGROUPID = c.String(),
                        WRKCTRTASKDEMAND = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PROPERTYLIMITED = c.Int(nullable: false),
                        QTYCATEGORYID = c.String(),
                        ROUTEGROUPID = c.String(),
                        ACCOUNTWRKCTRISSUEOFFSET = c.String(),
                        IWS_DEFAULTPRIORITY = c.Int(nullable: false),
                        IWS_JIXING = c.String(),
                        IWS_BEIZHU = c.String(),
                        IWS_PEIZHI = c.String(),
                        IWS_SENSITIVITY = c.String(),
                        IWS_JIXINGXINGHAO = c.String(),
                        IWS_VISIBLE = c.Int(nullable: false),
                        IWS_LOCATIONIDEXPORT = c.String(),
                        IWS_TIMECATEGORYGROUPID = c.String(),
                        IWS_COSTCATEGORYGROUPID = c.String(),
                        IWS_CAMENABLED = c.Int(nullable: false),
                        IWS_MACHINETYPE = c.Int(nullable: false),
                        QY_MAINMACHINE = c.Int(nullable: false),
                        QY_WRKQTY = c.Int(nullable: false),
                        QY_ISSTOP = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.WRKCTRTABLE");
            DropTable("dbo.ROUTEOPRTABLE");
            DropTable("dbo.QY_CHECK_TPTABLE");
            DropTable("dbo.QY_CHECK_CDTABLE");
            DropTable("dbo.PRODTABLE");
            DropTable("dbo.PRODROUTE");
            DropTable("dbo.PRODJOURNALROUTE");
            DropTable("dbo.PRODJOURNALBOM");
            DropTable("dbo.PRODBOM");
            DropTable("dbo.IWS_PRODUCTPARAMETER");
            DropTable("dbo.IWS_JINGDUQUEXIANPARAMETER");
            DropTable("dbo.IWS_CUSTPARATRADETABLE");
            DropTable("dbo.IWS_CHECK_WASHTABLE");
            DropTable("dbo.IWS_CHECK_REPAIRTABLE");
            DropTable("dbo.IWS_CHECK_PELLICLETABLE");
            DropTable("dbo.IWS_CHECK_LONGSIZETABLE");
            DropTable("dbo.IWS_CHECK_INNERPACKTABLE");
            DropTable("dbo.IWS_CHECK_AOITABLE");
            DropTable("dbo.IWS_CAMDESIGNPARAMTABLE");
            DropTable("dbo.IWS_CAMCRAFTCMDTRADETABLE");
            DropTable("dbo.IWS_CAMCRAFTCMDMATERIALTABLE");
            DropTable("dbo.IWS_CAMCRAFTCMDEQPCONFIGTABLE");
            DropTable("dbo.H_EQUIPMENTALARM");
            DropTable("dbo.H_EQUIPMENT_REPAIR");
            DropTable("dbo.H_EQUIPMENT_PHOTOETCHING");
        }
    }
}
