// <auto-generated />
namespace QYMSERVER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Machinesadddefaultvalue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Machinesadddefaultvalue));
        
        string IMigrationMetadata.Id
        {
            get { return "202001180733151_Machines add default value"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
